version: "3"

services:
  bot:
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    restart: always
    env_file: .env
    networks:
      - music-room

networks:
  music-room:
    external: true
