version: "3"

services:
  bot:
    build:
      dockerfile: ./deploy/Dockerfile
      context: .
    depends_on:
      - redis
    restart: always
    env_file: .env
    networks:
      - default
      - music-room

  redis:
    build: ./redis
    restart: always
    volumes:
      - redis:/data

networks:
  music-room:
    external: true
    name: music-room

volumes:
  redis:
